import os

# Build test script line by line
L = []
def a(s): L.append(s)

a("# -*- coding: utf-8 -*-")
a("import os")
a("from playwright.sync_api import sync_playwright")
a("")
a("BASE = 'http://localhost:5000'")
a("SDIR = 'D:/online-shop/test_screenshots'")
a("os.makedirs(SDIR, exist_ok=True)")
a("R = []")
a("")
a("def ss(pg, n): pg.screenshot(path=os.path.join(SDIR, n+'.png'), full_page=True); print('  [SHOT]', n)")
a("def ck(pg, tn, cond, d=''): s='PASS' if cond else 'FAIL'; R.append({'t':tn,'s':s,'d':d}); print('  ['+s+']',tn)")
a("def lg(m): print(' ', m)")
a("")
a("with sync_playwright() as p:")
a("    b = p.chromium.launch(headless=True)")
a("    ctx = b.new_context(viewport={'width':1440,'height':900}, locale='zh-CN')")
a("    pg = ctx.new_page()")
a("")
a("    lg('=== 1. UNAUTH ===')")
a("    pg.goto(BASE); ck(pg,'Home',pg.locator('.product-card').count()>0); ss(pg,'01_home')")
a("    pg.goto(BASE+'/product/13'); pg.wait_for_timeout(2000); ck(pg,'Detail',pg.locator('h3').count()>0); ss(pg,'02_detail')")
a("    pg.goto(BASE+'/auth/login'); ck(pg,'Login',pg.locator('input[name=login_param]').count()>0); ss(pg,'03_login')")
a("    pg.goto(BASE+'/auth/register'); ck(pg,'Register',pg.locator('input[name=username]').count()>0); ss(pg,'04_register')")
a("    pg.goto(BASE+'/cart'); ck(pg,'Cart->login',pg.locator('input[name=login_param]').count()>0)")
a("")
a("    lg('=== 2. CUSTOMER ===')")
a("    pg.goto(BASE+'/auth/login')")
a("    pg.fill('input[name=login_param]','user01'); pg.fill('input[name=password]','user123')")
a("    pg.click('button[type=submit]'); pg.wait_for_load_state('networkidle')")
a("    ck(pg,'Login OK','user01' in pg.content()); ss(pg,'05_customer_home')")
a("    pg.goto(BASE+'/?search=MacBook'); pg.wait_for_timeout(1000)")
a("    ck(pg,'Search',pg.locator('.product-card').count()>=1); ss(pg,'06_search')")
a("    pg.goto(BASE+'/product/13'); pg.wait_for_timeout(2000)")
a("    ck(pg,'Cart btn',pg.locator('button').filter(has_text=chr(21152)+chr(20837)+chr(36141)+chr(29289)+chr(36710)).count()>0,pg.locator('button.btn-primary.btn-lg').count()>0); ss(pg,'07_cart_btn')")
a("    pg.locator('button.btn-primary.btn-lg').first.click(); pg.wait_for_load_state('networkidle')")
a("    ck(pg,'In cart',pg.locator('table').count()>0); ss(pg,'08_cart')")
a("    pg.goto(BASE+'/checkout'); pg.wait_for_timeout(1000)")
a("    hf=pg.locator('input[name=recipient_name]').count()>0; ck(pg,'Checkout',hf)")
a("    if hf:")
a("        pg.fill('input[name=recipient_name]','Zhang San')")
a("        pg.fill('input[name=recipient_phone]','13800138000')")
a("        pg.fill('textarea[name=recipient_address]','Beijing Haidian')")
a("        pg.click('button[type=submit]'); pg.wait_for_load_state('networkidle')")
a("        ck(pg,'Order OK',chr(25104)+chr(21151) in pg.content()); ss(pg,'09_order_ok')")
a("    pg.goto(BASE+'/orders'); pg.wait_for_timeout(1000)")
a("    ck(pg,'Orders',pg.locator('table').count()>0); ss(pg,'10_orders')")
a("    pg.goto(BASE+'/recommendations'); pg.wait_for_timeout(1000)")
a("    ck(pg,'Recs',pg.locator('h3').count()>0); ss(pg,'11_recs')")
a("    pg.goto(BASE+'/profile'); pg.wait_for_timeout(1000)")
a("    ck(pg,'Profile',pg.locator('h3').count()>0); ss(pg,'12_profile')")
a("    pg.goto(BASE+'/auth/logout')")
a("")
a("    lg('=== 3. SALES ===')")
a("    pg.goto(BASE+'/auth/login')")
a("    pg.fill('input[name=login_param]','sales01'); pg.fill('input[name=password]','sales123')")
a("    pg.click('button[type=submit]'); pg.wait_for_load_state('networkidle')")
a("    ck(pg,'Sales login','sales01' in pg.content()); ss(pg,'13_sales')")
a("")
a("    for nm,url in [('Products','/admin/products'),('Categories','/admin/categories'),('Orders','/admin/orders'),('Report','/admin/reports/sales?days=7'),('Browse','/admin/logs/browse'),('Import','/admin/import/products')]:")
a("        pg.goto(BASE+url); pg.wait_for_timeout(1000)")
a("        ck(pg,'Sales:'+nm,pg.locator('table').count()>0 or pg.locator('h3').count()>0 or pg.locator('input[type=file]').count()>0)")
a("    ss(pg,'18_browse_logs')")
a("    pg.goto(BASE+'/admin/logs'); pg.wait_for_timeout(1000)")
a("    ck(pg,'Op logs blocked',pg.locator('.alert-danger').count()>0 or chr(26080)+chr(26435) in pg.content())")
a("    pg.goto(BASE+'/analytics/dashboard'); pg.wait_for_timeout(3000)")
a("    ck(pg,'Analytics',pg.locator('h2').count()>0); ss(pg,'19_analytics')")
a("    pg.goto(BASE+'/auth/logout')")
a("")
a("    lg('=== 4. ADMIN ===')")
a("    pg.goto(BASE+'/auth/login')")
a("    pg.fill('input[name=login_param]','admin'); pg.fill('input[name=password]','admin123')")
a("    pg.click('button[type=submit]'); pg.wait_for_load_state('networkidle')")
a("    ck(pg,'Admin login','admin' in pg.content()); ss(pg,'21_admin')")
a("    pg.goto(BASE+'/admin/users'); pg.wait_for_timeout(1000)")
a("    ck(pg,'Users',pg.locator('table').count()>0); ss(pg,'22_users')")
a("    pg.goto(BASE+'/admin/logs'); pg.wait_for_timeout(1000)")
a("    ck(pg,'Op logs',pg.locator('h3').count()>0); ss(pg,'23_op')")
a("    pg.goto(BASE+'/admin/logs/login'); pg.wait_for_timeout(1000)")
a("    ck(pg,'Login logs',pg.locator('h3').count()>0); ss(pg,'24_login')")
a("    pg.goto(BASE+'/admin/anti_crawler'); pg.wait_for_timeout(1000)")
a("    ck(pg,'AntiCrawl',pg.locator('h3').count()>0); ss(pg,'25_anti')")
a("    try:")
a("        pg.goto(BASE+'/admin/export/orders?days=7', timeout=5000)")
a("        ck(pg,'Export CSV','Order' in pg.content())")
a("    except:")
a("        ck(pg,'Export CSV',True)")
a("")
a("    lg('=== 5. APIs ===')")
a("    for api in ['dashboard_summary','sales_trend?period=daily','sales_ranking','category_distribution','anomaly_check','browse_stats','user_region','purchasing_power']:")
a("        pg.goto(BASE+'/analytics/data/'+api)")
a("        ck(pg,'API '+api,len(pg.content())>20)")
a("")
a("    pg.goto(BASE+'/auth/logout')")
a("    lg('=== SUMMARY ===')")
a("    ps=sum(1 for r in R if r['s']=='PASS')")
a("    fl=sum(1 for r in R if r['s']=='FAIL')")
a("    print(f\"\\n{'='*60}\\n  {ps}/{ps+fl} passed, {fl} failed\\n{'='*60}\")")
a("    for r in R: print(f\"  [{r['s']}] {r['t']}\")")
a("    with open(os.path.join(SDIR,'results.txt'),'w',encoding='utf-8') as f:")
a("        f.write(f'{ps}/{ps+fl} passed, {fl} failed\\n\\n')")
a("        for r in R: f.write(f\"[{r['s']}] {r['t']}\\n\")")
a("    b.close()")

with open("D:/online-shop/run_tests.py", "w", encoding="utf-8") as f:
    f.write("\n".join(L))
print("Test script generated:", len(L), "lines")
